In [1]:
import numpy as np

In [12]:
def encrypt(matrix,words):
    cipher=""
    length=len(matrix)
    matrix=np.array(matrix)
    words=words.lower()
    arr=[ord(i)-ord('a')for i in words]
    count=0
    for ch in words:
        if str.isalpha(str(ch)):
            cipher += chr(sum(matrix[count%length]*arr)%26+ord('a'))
            count += 1
    return cipher

In [20]:
def decrypt(matrix,words):
    cipher=""
    length=len(matrix)
    matrix=(np.linalg.inv(matrix)+26)%26
    words=words.lower()
    arr=np.array([ord(i)-ord('a') for i in words],dtype=int)
    count =0
    for ch in words:
        if str.isalpha(str(ch)):
            number=sum(matrix[count%length]*arr)%26
            print number
            cipher += chr(int(number)+ord('a'))
            count+=1
    return cipher

In [21]:
secret = [[ 8,  6,  9, 5  ],
              [ 6,  9,  5, 10 ],
              [ 5,  8,  4, 9  ],
              [ 10, 6, 11, 4  ]]
    # 明文
text = "hill";

    # 使用密匙（矩阵）加密字符串
ciphertext = encrypt(secret, text)

    # 密文
print(ciphertext)

[[ 8  6  9  5]
 [ 6  9  5 10]
 [ 5  8  4  9]
 [10  6 11  4]]
ytix


In [22]:
print(decrypt(secret, ciphertext))

7.0
8.0
11.0
11.0
gilk
